name: CI

on: push

jobs:
  library:
    runs-on: macos-12
    
    steps:
      - uses: actions/checkout@v3
      - name: Select Xcode 14
        run: sudo xcode-select -s /Applications/Xcode_14.1.app
      - name: Build
        run: swift build -v
      - name: Test
        run: swift test -v
